---
title: "Transect_rcode"
author: "Anya"
date: "2024-08-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Supplemental R code: All R code used to test hypotheses and generate figures for the manuscript.



```{r}
#Setting up the workspace 

#laod packages
library(ggplot2)
library(permute)
library(lattice)
library(vegan)
library(dplyr)
library(magrittr)
library(scales)
library(grid)
library(reshape2)
library(phyloseq)
library(randomForest)
library(knitr)
library(ggplot2)
library(tibble)
library(tidyverse)
library(vegan)
library(RColorBrewer)
library(readr)
library(ggpubr)
library(ggthemes)
library(rstatix)

physeq <- readRDS("Rp_physeq.rds")

#function for calculating mean/sd (used throughout)
mean.sd <- function(x) c(mean = mean(x), sd = sd(x))

#transform raw data to relative abundance 
Rp_physeq_ab <- Rp_physeq %>% transform_sample_counts(function(x) {x/sum(x)} )

#Subset  leaf samples from soil and remove rows(ASVs) with zero sum
L_Rp_physeq_ab <- subset_samples(Rp_physeq_ab, Type %in% c("Leaf "))
data <- otu_table(L_Rp_physeq_ab)
data = data[ rowSums(data)!=0, ] 
otu_table(L_Rp_physeq_ab) <- otu_table(data, taxa_are_rows = TRUE) 

#Subset leaf phyloseq into individual host species
species <- dput(sample_data(L_Rp_physeq_ab)$Host_species)
species_list <- factor(species)

for(i in levels(species_list)) {
  data <- subset_samples(L_Rp_physeq_ab, Host_species %in% i)
  data_otu <- otu_table(data)
  data_otu = data_otu[ rowSums(data_otu)!=0, ] 
  otu_table(data) <- otu_table(data_otu, taxa_are_rows = TRUE) 
  new_name <- paste0(i,"_Rp_physeq_ab")
  assign(new_name, data)
  print(new_name)
}

###########################################
####Manuka phyllosphere core microbiome####
###########################################

set.seed(1)
data <- Manuka_Rp_physeq_ab
n <- nsamples(data)
mean <- rowMeans(otu_table(data))
occupancy = rowSums(otu_table(data) != 0)/n
tax <- tax_table(data)

df <- data.frame(tax, Abundance = mean, Occupancy = occupancy)
df[,c(8)] <- log10(df[,c(8)])
df$colour <- ifelse(df$Occupancy > 0.99, "core", "noncore")
table(df$colour) #number of core vs. noncore ASVs

#creating a specific manuka core dataframe
manuka_coretax <- filter(df, colour == 'core') %>%
  select(., -c("Abundance", "Occupancy", "colour")) 
c <- row.names(manuka_coretax)
core_otu <- subset(otu_table(Manuka_Rp_physeq_ab), row.names(otu_table(Manuka_Rp_physeq_ab)) %in% c)
core_Manuka_Rp_physeq_ab <- Manuka_Rp_physeq_ab
otu_table(core_Manuka_Rp_physeq_ab) <- otu_table(core_otu, taxa_are_rows = TRUE) 
colnames(tax_table(core_Manuka_Rp_physeq_ab))[7] <- "ASV"
groups <- rownames(tax_table(core_Manuka_Rp_physeq_ab))
tax_table(core_Manuka_Rp_physeq_ab)[,"ASV"] <- groups

###Fig4a###
Fig4a <-  ggplot(df, aes(x=Abundance, y=Occupancy, color = colour)) + geom_point(size = 3, alpha = 0.5, position = "jitter") +
  xlab("Relative abundance (log10)") +
  ylab("Prevalence") +
  theme(legend.position="right",
        legend.key.height = unit(0.3, "cm"),
        #legend.title = element_blank(),
        legend.key=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title = element_text(size=12),
        strip.text.x = element_text(size = 12),
        strip.text.y = element_text(size = 12),
        axis.line = element_line()) +
  scale_color_manual(values=c(core="violetred3", noncore= "grey40")) +
  scale_y_continuous(expand = expansion(mult = c(0, .05))) ;Fig4a

Fig4a$labels$colour <- "ASVs" ;Fig4a

################################################
####Non-manuka phyllosphere core microbiomes####
################################################

#kanuka
set.seed(1)
data <- Kanuka_Rp_physeq_ab
n <- nsamples(data)
mean <- rowMeans(otu_table(data))
occupancy = rowSums(otu_table(data) != 0)/n
tax <- tax_table(data)

df2 <- data.frame(tax, Abundance = mean, Occupancy = occupancy)
df2[,c(8)] <- log10(df2[,c(8)]) #log 10 transformation
df2$colour <- ifelse(df2$Occupancy > 0.99, "core", "noncore")
table(df2$colour) #number of core vs. noncore ASVs

#create kanuka core object
kan_212core <- filter(df2, colour == "core")
kan_asvs <- rownames(kan_212core)
kancore_otu <- subset(otu_table(Kanuka_Rp_physeq_ab), rownames(otu_table(Kanuka_Rp_physeq_ab)) %in% kan_asvs)
Kan_core_physeq <- Kanuka_Rp_physeq_ab
Kan_core_physeq <- merge_phyloseq(kancore_otu, tax_table(Kanuka_Rp_physeq_ab), sample_data(Kanuka_Rp_physeq_ab))

SFig5a <- ggplot(df2, aes(x=Abundance, y=Occupancy, color = colour)) + geom_point(size = 3, alpha = 0.5, position = "jitter") +
  xlab("Relative abundance (log10)") +
  ylab("Prevalence") +
  theme(legend.position="none",
        legend.title = element_blank(),
        legend.key=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title = element_text(size=12),
        strip.text.y = element_text(size = 12),
        strip.text.x = element_text(size = 12),
        axis.line = element_line()) +
   scale_y_continuous(expand = expansion(mult = c(0, .04))) +
  scale_color_manual(values=c(core="violetred3", noncore= "grey40")) +
   annotate(geom="text", x=-4.75, y=0.95, label="Kānuka", color="black"); SFig5a

#tawiniwini
set.seed(1)
data <- Tawiniwini_Rp_physeq_ab
n <- nsamples(data)
mean <- rowMeans(otu_table(data))
occupancy = rowSums(otu_table(data) != 0)/n
tax <- tax_table(data)

df2 <- data.frame(tax, Abundance = mean, Occupancy = occupancy)
df2[,c(8)] <- log10(df2[,c(8)]) #log 10 transformation
df2$colour <- ifelse(df2$Occupancy > 0.99, "core", "noncore")
table(df$colour) #number of core vs. noncore ASVs

#creating tawiniwini core object
taw_209core <- filter(df2, colour == "core")
taw_asvs <- rownames(taw_209core)
tawcore_otu <- subset(otu_table(Tawiniwini_Rp_physeq_ab), rownames(otu_table(Tawiniwini_Rp_physeq_ab)) %in% taw_asvs)
Taw_core_physeq <- Tawiniwini_Rp_physeq_ab
Taw_core_physeq <- merge_phyloseq(tawcore_otu, tax_table(Tawiniwini_Rp_physeq_ab), sample_data(Tawiniwini_Rp_physeq_ab))

SFig5b <- ggplot(df2, aes(x=Abundance, y=Occupancy, color = colour)) + 
  geom_point(size = 3, alpha = 0.5, position = "jitter") +
  xlab("Relative abundance (log10)") +
  ylab("Prevalence") +
   theme(legend.position="none",
        legend.title = element_blank(),
        legend.key=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title = element_text(size=12),
        strip.text.y = element_text(size = 12),
        strip.text.x = element_text(size = 12),
        axis.line = element_line()) +
   scale_y_continuous(expand = expansion(mult = c(0, .04))) +
  scale_color_manual(values=c(core="violetred3", noncore= "grey40"))  +
   annotate(geom="text", x=-4.75, y=0.95, label="Tawiniwini", color="black"); SFig5b

#toatoa 
set.seed(1)
data <- Toatoa_Rp_physeq_ab
n <- nsamples(data)
mean <- rowMeans(otu_table(data))
occupancy = rowSums(otu_table(data) != 0)/n
tax <- tax_table(data)

df2 <- data.frame(tax, Abundance = mean, Occupancy = occupancy)
df2[,c(8)] <- log10(df2[,c(8)]) #log 10 transformation
df2$colour <- ifelse(df2$Occupancy > 0.99, "core", "noncore")
table(df2$colour) #number of core vs. noncore ASVs

#creating toatoa core object
toa_92core <- filter(df2, colour == "core")
toa_asvs <- rownames(toa_92core)
toacore_otu <- subset(otu_table(Toatoa_Rp_physeq_ab), rownames(otu_table(Toatoa_Rp_physeq_ab)) %in% toa_asvs)
Toatoa_core_physeq <- Toatoa_Rp_physeq_ab
Toatoa_core_physeq <- merge_phyloseq(toacore_otu, tax_table(Toatoa_Rp_physeq_ab), sample_data(Toatoa_Rp_physeq_ab))

SFig5c <- ggplot(df2, aes(x=Abundance, y=Occupancy, color = colour)) + geom_point(size = 3, alpha = 0.5, position = "jitter") +
  xlab("Relative abundance (log10)") +
  ylab("Prevalence") +
  theme(legend.position="none",
        legend.title = element_blank(),
        legend.key=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title = element_text(size=12),
        strip.text.y = element_text(size = 12),
        strip.text.x = element_text(size = 12),
        axis.line = element_line()) +
   scale_y_continuous(expand = expansion(mult = c(0, .04))) +
  scale_color_manual(values=c(core="violetred3", noncore= "grey40")) +
   annotate(geom="text", x=-4.85, y=0.95, label="Toatoa", color="black"); SFig5c

#surfacesoil
#Subset Rp soil samples and remove rows(ASVs) with zero sum
S_Rp_physeq_ab <- subset_samples(Rp_physeq_ab, Type %in% c("Soil"))
data <- otu_table(S_Rp_physeq_ab)
data = data[ rowSums(data)!=0, ] 
otu_table(S_Rp_physeq_ab) <- otu_table(data, taxa_are_rows = TRUE) 

set.seed(1)
data <- S_Rp_physeq_ab
n <- nsamples(data)
mean <- rowMeans(otu_table(data))
occupancy = rowSums(otu_table(data) != 0)/n
tax <- tax_table(data)

df2 <- data.frame(tax, Abundance = mean, Occupancy = occupancy)
df2[,c(8)] <- log10(df2[,c(8)]) #definitely better with log 10 transformation
df2$colour <- ifelse(df2$Occupancy > 0.99, "core", "noncore")
table(df2$colour) #number of core vs. noncore ASVs

SFig5d <- ggplot(df2, aes(x=Abundance, y=Occupancy, color = colour)) + geom_point(size = 3, alpha = 0.5, position = "jitter") +
  xlab("Relative abundance (log10)") +
  ylab("Prevalence") +
  theme(legend.position="none",
        legend.title = element_blank(),
        legend.key=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title = element_text(size=12),
        strip.text.x = element_text(size = 12),
        axis.line = element_line()) +
    ylim(0,1) +
  scale_y_continuous(expand = expansion(mult = c(0, .15))) +
  scale_color_manual(values=c(core="violetred3", noncore= "grey40")) +
   annotate(geom="text", x=-5.5, y=0.95, label="Soil", color="black"); SFig5d

###plotting SFig5###
SFig5 <- plot_grid(SFig5a, SFig5b, SFig5c, SFig5d,
               labels = c('A', 'B', 'C', 'D'),
               ncol= 2,
               label_size = 12); SFig5

ggsave(filename = "SFig5.png", plot = SFig5, width = 20, height = 17, units = c("cm"))

###Fig4b###
 s <-  as.data.frame(colSums(otu_table(core_Manuka_Rp_physeq_ab)))
 colnames(s)[1] = "Cumab"
  t <-  as.data.frame(colSums(otu_table(Taw_core_physeq )))
 colnames(t)[1] = "Cumab"
 u <-  as.data.frame(colSums(otu_table(Toatoa_core_physeq)))
 colnames(u)[1] = "Cumab"
  v <-  as.data.frame(colSums(otu_table(Kan_core_physeq )))
 colnames(v)[1] = "Cumab"
 
 h <- rbind(s,t, u, v)
 h$Sample_ID <- rownames(h)
 meta = as(sample_data(L_Rp_physeq_ab), "data.frame")

df <- merge(h, meta, by = "Sample_ID") 
df$Host_species <- factor(df$Host_species,
       c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")) #this reorders

box2 <- ggplot(df, aes (x = Host_species, y = Cumab, fill = Host_species)) + 
  geom_boxplot(outlier.shape=NA) + 
  scale_x_discrete(labels=c("Mānuka", "Kānuka", "Tawiniwini", "Toatoa")) +
  scale_fill_manual(name = "Plant species", values = mycols, 
                    labels=c("Mānuka", "Kānuka", "Tawiniwini", "Toatoa")) +
  geom_jitter(size = 2, width=0.2,height=NULL) + 
  
  ylim(0,1) + 
  ylab("Relative abundance") + 
  xlab("Plant species") + 
  theme_classic(base_size = 12) + 
  theme(legend.position="none") ; box2

my_comparisons <- list(c ("Manuka", "Tawiniwini"),
                       c ("Manuka", "Toatoa"), 
                       c ("Kanuka", "Tawiniwini"), 
                       c ("Kanuka", "Toatoa"))

Fig4b <- box2 + 
            stat_compare_means(label.y = 0.05, aes(label = sprintf("Kruskal test, p = %5.5f", as.numeric(..p.format..)))) +
            stat_compare_means(comparisons = my_comparisons,
                                symnum.args = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf), 
                                                   symbols = c("***", "**", "*", "ns", "ns")),
                               
                               label = "p.signif",  
                               label.y = c(.72, .8, .88, .96), 
                               method = "t.test") ; Fig4b

###Fig4C###
q <- rownames(toa_92core)
r <- rownames(taw_209core)
f <- rownames(kan_212core)
g <- rownames(manuka_coretax)

p <- as.data.frame(cbind(q,"1"))
colnames(p)[2] = "Toatoa"
row.names(p) <- p[,1]
colnames(p)[1] = "ASVs"

h <- as.data.frame(cbind(r,"1"))
colnames(h)[2] = "Tawiniwini"
row.names(h) <- h[,1]
colnames(h)[1] = "ASVs"

n <- as.data.frame(cbind(f,"1"))
colnames(n)[2] = "Kānuka"
row.names(n) <- n[,1]
colnames(n)[1] = "ASVs"

d <- as.data.frame(cbind(g,"1"))
colnames(d)[2] = "Mānuka"
row.names(d) <- d[,1]
colnames(d)[1] = "ASVs"

merged <- dplyr::full_join(d, n, by = "ASVs") %>%
          dplyr::full_join(., h, by = "ASVs") %>%
          dplyr::full_join(., p, by = "ASVs") 
  row.names(merged) <- merged[,1]
  m2 <- merged %>% select("Mānuka", "Kānuka", "Toatoa", "Tawiniwini") 
  
  m2[,1] <- as.numeric(as.character(m2$Mānuka))
  m2[,2] <- as.numeric(as.character(m2$Kānuka))
  m2[,3] <- as.numeric(as.character(m2$Toatoa))
  m2[,4] <- as.numeric(as.character(m2$Tawiniwini))
  
  genres = colnames(m2)[1:4]

library(ComplexUpset)
#input = species (list of species) & c_otu (table)

Fig4c <- ComplexUpset::upset(m2, genres, name = 'Plant species', height_ratio=.38, width_ratio=0.2,
                         
        
        base_annotations = list(
        'Intersection size'=(
            intersection_size(
                width = 0.9,
                
         
              counts=T, text = aes(size = 4))
            + ylab('Number of Core ASVs') 
           + theme(axis.ticks.y=element_line(),
                    axis.text.y = element_text(size=11),
                    axis.text.x = element_blank(),
                    axis.title.y=element_text(size=12))
        )),
        
        
        set_sizes=(
        upset_set_size() +
        theme_classic() +
           ylab("Total") +
          theme(axis.ticks.x=element_line(),
                axis.text.x=element_text(size=10, angle = 45, vjust = 0.8),
                axis.title.x = element_text(size = 11),
                axis.line.y = element_blank(),
                axis.title.y = element_blank(),
                axis.text.y = element_blank(),
                axis.ticks.y = element_blank())
        ),
                                
        queries = list(
       
         upset_query(
          intersect=c("Mānuka", "Kānuka", "Tawiniwini"),
          color = "#DDAA33", 
          fill = "#DDAA33",
          only_components=c('intersections_matrix', 'Intersection size')
        ),
        
         upset_query(
          intersect=c("Mānuka", "Toatoa", "Tawiniwini", 
                      "Kānuka"),
          color = "#DDAA33", 
          fill = "#DDAA33",
          only_components=c('intersections_matrix', 'Intersection size')
        ),
          
        upset_query(
          intersect=c("Mānuka", "Kānuka"),
          color = "#DDAA33", 
          fill = "#DDAA33",
          only_components=c('intersections_matrix', 'Intersection size')
        ),
        
       upset_query(
          intersect=c("Mānuka", "Tawiniwini"),
          color = "#DDAA33", 
          fill = "#DDAA33",
          only_components=c('intersections_matrix', 'Intersection size')
        ),
       
       upset_query(
          intersect=c("Mānuka", "Toatoa"),
          color = "#DDAA33", 
          fill = "#DDAA33",
          only_components=c('intersections_matrix', 'Intersection size')
        ),
       
       upset_query(
          intersect=c("Mānuka", "Kānuka", "Toatoa"),
          color = "#DDAA33", 
          fill = "#DDAA33",
          only_components=c('intersections_matrix', 'Intersection size')
        ),
       
      
       upset_query(
          intersect=c("Mānuka", "Toatoa", "Tawiniwini"),
          color = "#DDAA33", 
          fill = "#DDAA33",
          only_components=c('intersections_matrix', 'Intersection size') 
        ))) ; Fig4c

###Fig4D###
##Look at relative abundance of manuka core taxa across all host species
c <- row.names(manuka_coretax)
core_otu_allsamples <- subset(otu_table(L_Rp_physeq_ab), row.names(otu_table(L_Rp_physeq_ab)) %in% c)
mancore_alln_Rp_physeq_ab <- L_Rp_physeq_ab
otu_table(mancore_alln_Rp_physeq_ab) <- otu_table(core_otu_allsamples, taxa_are_rows = TRUE) 

colnames(tax_table(mancore_alln_Rp_physeq_ab))[7] <- "ASV"
groups <- rownames(tax_table(mancore_alln_Rp_physeq_ab))
tax_table(mancore_alln_Rp_physeq_ab)[,"ASV"] <- groups

#manuka core - in kanuka
mancore_kan_Rp_physeq_ab <- subset_samples(mancore_alln_Rp_physeq_ab, Host_species %in% c("Kanuka"))
data <- otu_table(mancore_kan_Rp_physeq_ab)
data = data[ rowSums(data)!=0, ] 
otu_table(mancore_kan_Rp_physeq_ab) <- otu_table(data, taxa_are_rows = TRUE) 

#manuka core - in tawiniwini
mancore_taw_Rp_physeq_ab <- subset_samples(mancore_alln_Rp_physeq_ab, Host_species %in% c("Tawiniwini"))
data <- otu_table(mancore_taw_Rp_physeq_ab)
data = data[ rowSums(data)!=0, ] 
otu_table(mancore_taw_Rp_physeq_ab) <- otu_table(data, taxa_are_rows = TRUE) 

#manuka core - in toatoa
mancore_toa_Rp_physeq_ab <- subset_samples(mancore_alln_Rp_physeq_ab, Host_species %in% c("Toatoa"))
data <- otu_table(mancore_toa_Rp_physeq_ab)
data = data[ rowSums(data)!=0, ] 
otu_table(mancore_toa_Rp_physeq_ab) <- otu_table(data, taxa_are_rows = TRUE) 

s <-  as.data.frame(colSums(otu_table(core_Manuka_Rp_physeq_ab)))
 colnames(s)[1] = "Cumab"
t <-  as.data.frame(colSums(otu_table(mancore_taw_Rp_physeq_ab)))
 colnames(t)[1] = "Cumab"
u <-  as.data.frame(colSums(otu_table(mancore_toa_Rp_physeq_ab)))
 colnames(u)[1] = "Cumab"
v <-  as.data.frame(colSums(otu_table(mancore_kan_Rp_physeq_ab)))
 colnames(v)[1] = "Cumab"
 
 h <- rbind(s,t, u, v)
 h$Sample_ID <- rownames(h)
 meta = as(sample_data(L_Rp_physeq_ab), "data.frame")

df <- merge(h, meta, by = "Sample_ID") 
df$Host_species <- factor(df$Host_species,
       c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")) #this reorders

mycols <- c( "#DDAA33", "#44AA99", "#004488",   "#bb5566")

box1 <- ggplot(df, aes (x = Host_species, y = Cumab, fill = Host_species)) + 
  geom_boxplot(outlier.shape=NA) + 
  scale_x_discrete(labels=c("Mānuka", "Kānuka", "Tawiniwini", "Toatoa")) +
  scale_fill_manual(name = "Plant species", values = mycols, 
                    labels=c("Mānuka", "Kānuka", "Tawiniwini", "Toatoa")) +
  geom_jitter(size = 2, width=0.2,height=NULL) + 
  
  ylim(0,1) + 
  ylab("Relative abundance") + 
  xlab("Plant species") + 
  theme_classic(base_size = 12) + 
  theme(legend.position="none") ; box1 

Fig4d <- box1 + 
            stat_compare_means(label.y = 0.05, aes(label = sprintf("Kruskal test, p = %5.4f", as.numeric(..p.format..)))) +
            stat_compare_means(comparisons = my_comparisons,
                                symnum.args = list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf), 
                                                   symbols = c("***", "**", "**", "ns", "ns")),
                               label = "p.signif",  
                              label.y = c(.72, .8, .88, .96),   
                               method = "t.test") ; Fig4d

###Core taxonomy###
#SFig4A
data <- mancore_alln_Rp_physeq_ab %>%                                         
  tax_glom(taxrank = "Genus") %>%                     
  psmelt() %>%                   
  arrange(-Abundance) 

data$Host_species <- factor(data$Host_species, levels=c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")) #establishes the x axis order
host.labs <- c("Mānuka", "Kānuka", "Tawiniwini", "Toatoa")
names(host.labs) <- c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")

#customise facet box colours
library(ggh4x)
M_core <- ggplot(data, aes(x=Sample_ID, y = Abundance, fill = Genus)) +
  
  geom_bar(stat = "identity", width = 0.8, show.legend = TRUE) +
  
  xlab("") +
  ylab("Relative Abundance \n ") +
  scale_x_discrete(breaks = unique) +
  scale_y_continuous(limits = c(0,0.8), expand = c(0,0)) + 
  theme_classic() +
  theme(axis.text.x=element_blank()) +
  theme(legend.position = "none", legend.text = element_text(size=10, face = "italic"), legend.title = element_text(size = 10)) +
  
  facet_wrap2(ncol =4,
    Host_species ~ ., scales = "free", axes = TRUE,
    labeller = labeller(Host_species = host.labs),
    strip = strip_themed(
      background_x = list(element_rect(fill="lightgrey"),
                          element_rect(fill="white"),
                          element_rect(fill="white"),
                          element_rect(fill="white"))
                                       
    )) +
    scale_fill_manual(values = c("Acidiphilium" = "#8DD3C7",
                                "Aurantisolimonas" = "#FFFFB3",
                                "Bryocella" = "#BEBADA",
                                "Edaphobacter" =  "#FB8072",
                                "Granulicella" = "#80B1D3",
                                "LD29" = "#FDB462",
                                "Methylocella" = "#B3DE69",
                                "PMMR1" =   "#FCCDE5",
                                "Sphingomonas" = "#D9D9D9",
                                "Terriglobus" =  "#BC80BD",
                                "Unknown" = "#CCEBC5",
                                "1174-901-12" = "#FFED6F")) ; M_core

#Kanuka
goodTaxa <- kan_asvs #define taxa to keep
kancore_allln_Rp_physeq_ab = prune_taxa(goodTaxa, L_Rp_physeq_ab) #prune

data <- kancore_allln_Rp_physeq_ab %>%                                         
  tax_glom(taxrank = "Genus") %>%                     
  psmelt() %>%                   
  arrange(-Abundance) 
  
data$Host_species <- factor(data$Host_species, levels=c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")) #this establishes the x axis order
host.labs <- c("Mānuka", "Kānuka", "Tawiniwini", "Toatoa")
names(host.labs) <- c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")

#customise facet box colours
library(ggh4x)

K_core <- ggplot(data, aes(x=Sample_ID, y = Abundance, fill = Genus)) +
  geom_bar(stat = "identity", width = 0.8, show.legend = TRUE) +
  xlab("") +
  ylab("Relative Abundance \n ") +
  scale_x_discrete(breaks = unique) +
  scale_y_continuous(limits = c(0,0.8), expand = c(0,0)) + 
  theme_classic() +
  theme(axis.text.x=element_blank()) +
  theme(legend.position = "none", legend.text = element_text(size=10, face = "italic"), legend.title = element_text(size = 10)) +
  
  facet_wrap2(ncol =4,
    Host_species ~ ., scales = "free", axes = TRUE,
    labeller = labeller(Host_species = host.labs),
    strip = strip_themed(
      background_x = list(element_rect(fill="white"),
                          element_rect(fill="lightgrey"),
                          element_rect(fill="white"),
                          element_rect(fill="white"))
                                       
    )) +
    scale_fill_manual(values = c("Acidiphilium" = "#8DD3C7",
                                "Aurantisolimonas" = "#FFFFB3",
                                "Bryocella" = "#BEBADA",
                                "Edaphobacter" =  "#FB8072",
                                "Granulicella" = "#80B1D3",
                                "LD29" = "#FDB462",
                                "Methylocella" = "#B3DE69",
                                "PMMR1" =   "#FCCDE5",
                                "Sphingomonas" = "#D9D9D9",
                                "Terriglobus" =  "#BC80BD",
                                "Unknown" = "#CCEBC5",
                                "1174-901-12" = "#FFED6F")) ; K_core

#Tawiniwini data
goodTaxa <- taw_asvs #define taxa to keep
tawcore_allln_Rp_physeq_ab = prune_taxa(goodTaxa, L_Rp_physeq_ab) #prune

data <- tawcore_allln_Rp_physeq_ab %>%                                         
  tax_glom(taxrank = "Genus") %>%                     
  psmelt() %>%                   
  arrange(-Abundance) 
  
data$Host_species <- factor(data$Host_species, levels=c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")) #this establishes the x axis order
host.labs <- c("Mānuka", "Kānuka", "Tawiniwini", "Toatoa")
names(host.labs) <- c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")

#customise facet box colours
library(ggh4x)

Taw_core <- ggplot(data, aes(x=Sample_ID, y = Abundance, fill = Genus)) +
  geom_bar(stat = "identity", width = 0.8, show.legend = TRUE) +
  xlab("") +
  ylab("Relative Abundance \n ") +
  scale_x_discrete(breaks = unique) +
  scale_y_continuous(limits = c(0,0.8), expand = c(0,0)) + 
  theme_classic() +
  theme(axis.text.x=element_blank()) +
  theme(legend.position = "none", legend.text = element_text(size=10, face = "italic"), legend.title = element_text(size = 10)) +
  
  facet_wrap2(ncol =4,
    Host_species ~ ., scales = "free", axes = TRUE,
    labeller = labeller(Host_species = host.labs),
    strip = strip_themed(
      background_x = list(element_rect(fill="white"),
                          element_rect(fill="white"),
                          element_rect(fill="lightgrey"),
                          element_rect(fill="white"))
                                       
    )) +
    scale_fill_manual(values = c("Acidiphilium" = "#8DD3C7",
                                "Aurantisolimonas" = "#FFFFB3",
                                "Bryocella" = "#BEBADA",
                                "Edaphobacter" =  "#FB8072",
                                "Granulicella" = "#80B1D3",
                                "LD29" = "#FDB462",
                                "Methylocella" = "#B3DE69",
                                "PMMR1" =   "#FCCDE5",
                                "Sphingomonas" = "#D9D9D9",
                                "Terriglobus" =  "#BC80BD",
                                "Unknown" = "#CCEBC5",
                                "1174-901-12" = "#FFED6F")) ; Taw_core
#Toatoa data 
goodTaxa <- toa_asvs #define taxa to keep
toacore_allln_Rp_physeq_ab = prune_taxa(goodTaxa, L_Rp_physeq_ab) #prune

data <- toacore_allln_Rp_physeq_ab %>%                                         
  tax_glom(taxrank = "Genus") %>%                     
  psmelt() %>%                   
  arrange(-Abundance) 
  
data$Host_species <- factor(data$Host_species, levels=c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")) #this establishes the x axis order
host.labs <- c("Mānuka", "Kānuka", "Tawiniwini", "Toatoa")
names(host.labs) <- c("Manuka", "Kanuka", "Tawiniwini", "Toatoa")

#customise facet box colours
library(ggh4x)

To_core <- ggplot(data, aes(x=Sample_ID, y = Abundance, fill = Genus)) +
  geom_bar(stat = "identity", width = 0.8, show.legend = TRUE) +
  xlab("") +
  ylab("Relative Abundance \n ") +
  scale_x_discrete(breaks = unique) +
  scale_y_continuous(limits = c(0,0.8), expand = c(0,0)) + 
  theme_classic() +
  theme(axis.text.x=element_blank()) +
  theme(legend.position = "none", legend.text = element_text(size=10, face = "italic"), legend.title = element_text(size = 10)) +
  
  facet_wrap2(ncol =4,
    Host_species ~ ., scales = "free", axes = TRUE,
    labeller = labeller(Host_species = host.labs),
    strip = strip_themed(
      background_x = list(element_rect(fill="white"),
                          element_rect(fill="white"),
                          element_rect(fill="white"),
                          element_rect(fill="lightgrey"))
                                       
    )) +
    scale_fill_manual(values = c("Acidiphilium" = "#8DD3C7",
                                "Aurantisolimonas" = "#FFFFB3",
                                "Bryocella" = "#BEBADA",
                                "Edaphobacter" =  "#FB8072",
                                "Granulicella" = "#80B1D3",
                                "LD29" = "#FDB462",
                                "Methylocella" = "#B3DE69",
                                "PMMR1" =   "#FCCDE5",
                                "Sphingomonas" = "#D9D9D9",
                                "Terriglobus" =  "#BC80BD",
                                "Unknown" = "#CCEBC5",
                                "1174-901-12" = "#FFED6F")) ; To_core


#plotting manuka for legend 
data <- mancore_alln_Rp_physeq_ab %>%                                         
  tax_glom(taxrank = "Genus") %>%                     
  psmelt() %>%                   
  arrange(-Abundance) 

M_leg <- ggplot(data, aes(x=Sample_ID, y = Abundance, fill = Genus)) +
  geom_bar(stat = "identity", width = 0.8, show.legend = TRUE) +
  xlab("") +
  ylab("Relative Abundance \n ") +
  scale_x_discrete(breaks = unique) +
  scale_y_continuous(limits = c(0,0.8), expand = c(0,0)) + 
  theme_classic() +
  theme(axis.text.x=element_blank()) +
  theme(legend.position = "bottom", legend.text = element_text(size=12, face = "italic"), legend.title = element_text(size = 12)) +
  
  facet_wrap2(ncol =4,
    Host_species ~ ., scales = "free", axes = TRUE,
    labeller = labeller(Host_species = host.labs),
    strip = strip_themed(
      background_x = list(element_rect(fill="lightgrey"),
                          element_rect(fill="white"),
                          element_rect(fill="white"),
                          element_rect(fill="white"))
                                       
    )) +
    scale_fill_manual(values = c("Acidiphilium" = "#8DD3C7",
                                "Aurantisolimonas" = "#FFFFB3",
                                "Bryocella" = "#BEBADA",
                                "Edaphobacter" =  "#FB8072",
                                "Granulicella" = "#80B1D3",
                                "LD29" = "#FDB462",
                                "Methylocella" = "#B3DE69",
                                "PMMR1" =   "#FCCDE5",
                                "Sphingomonas" = "#D9D9D9",
                                "Terriglobus" =  "#BC80BD",
                                "Unknown" = "#CCEBC5",
                                "1174-901-12" = "#FFED6F")) ; M_leg

#extract legend
SFig4leg <- get_legend(M_leg)
as_ggplot(SFig4leg)
#saving the leg
ggsave(filename = "SFig4_legend.png", plot = SFig4leg, width = 21, height = 4, units = c("cm"))

SFig4 <- plot_grid(M_core, K_core, Taw_core, To_core, SFig4leg,
         labels = c('A', 'B', 'C', 'D'),
               ncol= 1,
               label_size = 12); SFig4

ggsave(filename = "SFig4.png", plot = SFig4, width = 21, height = 27, units = c("cm"))
```



